<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWMuqx8I\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWMuqx8I/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWMuqx8I.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWMuqx8I\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWMuqx8I\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WMuqx8I',
    'container.build_id' => '5dffdead',
    'container.build_time' => 1576504990,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWMuqx8I');
